version: '3.8'

services:
  photosync:
    build: .
    container_name: photosync-app
    ports:
      - "8080:3000"
    volumes:
      - ./photo-storage:/app/storage
      - ./server/data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  photo-storage:
    driver: local
  database:
    driver: local
