name: Simple pnpm Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Verify pnpm
        run: |
          echo "Testing pnpm installation..."
          pnpm --version
          echo "pnpm is working!"

      - name: Install root dependencies
        run: |
          echo "Installing root dependencies..."
          pnpm install
          echo "Root dependencies installed!"

      - name: Install client dependencies
        run: |
          echo "Installing client dependencies..."
          cd client
          pnpm install
          echo "Client dependencies installed!"

      - name: Install server dependencies
        run: |
          echo "Installing server dependencies..."
          cd server
          pnpm install
          echo "Server dependencies installed!"

      - name: Test build
        run: |
          echo "Testing build..."
          cd client
          pnpm run build
          echo "Build successful!"
